In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['axes.grid'] ="True"
mpl.rcParams['axes.spines.top'] = "True"
mpl.rcParams['axes.spines.right'] = "True"
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20

df_mls = pd.read_csv("../../data/MLS_1823_clean.csv")
df_mls = df_mls[(df_mls['Season'] != 2023) & (df_mls['Season'] != 2022) & (df_mls['Season'] != 2024)]

print(df_mls)
df_mls_matches = pd.read_csv("../../data/MLS_Matches_1823_clean.csv")
df_mls_matches = df_mls_matches[(df_mls_matches['Season'] != 2023) & (df_mls_matches['Season'] != 2022) & (df_mls_matches['Season'] != 2024)]




all_teams = df_mls["Team"].unique()

# print(len(df_mls_matches["Team"].unique()))
# print(len(all_teams))
# print(df_mls_matches)
# print(df_mls_matches["Team"].unique())
# print(all_teams)

    Unnamed: 0                    Team  Season  npxG  SCA  GCA  GF   Sh    xA  \
0            0             cf montreal    2018  39.9  717   80  47  418  28.3
1            1          houston dynamo    2018  53.7  825   96  58  470  35.8
2            2              toronto fc    2018  55.3  852   99  59  476  41.0
3            3               fc dallas    2018  52.8  849   90  52  477  32.4
4            4          atlanta united    2018  68.2  902  111  70  497  44.6
..         ...                     ...     ...   ...  ...  ...  ..  ...   ...
95          95          atlanta united    2021  42.9  825   77  45  449  30.4
96          96               fc dallas    2021  48.0  760   73  47  443  29.6
97          97              toronto fc    2021  42.0  603   65  39  347  33.0
98          98          houston dynamo    2021  42.5  743   59  36  422  27.2
99          99  new england revolution    2021  56.9  882  108  65  492  42.7

    SoT  Pts
0   130   46
1   178   38
2   172   36
3   168   57
4   187   69
..  ...  ...
95  148   51
96  144   33
97  124   28
98  136   30
99  174   73

[100 rows x 11 columns]

In [2]:
def calc_feats(df, team):
    team_stats = dict()
    df_team = df[(df["Team"]==team)]
    team_shots = df_team.apply(lambda x: x["Sh"], axis=1).sum()
    team_shots_ot = df_team.apply(lambda x: x["SoT"], axis=1).sum()
    team_shots_sca = df_team.apply(lambda x: x["SCA"], axis=1).sum()
    team_shots_gca = df_team.apply(lambda x: x["GCA"], axis=1).sum()
    team_shots_npxG = df_team.apply(lambda x: x["npxG"], axis=1).sum()
    team_shots_xA = df_team.apply(lambda x: x["xA"], axis=1).sum()
    team_points = df_team.apply(lambda x: x["Pts"], axis=1).sum()

    team_stats["team"] = team
    team_stats["shots"] = team_shots
    team_stats["shots_ot"] = team_shots_ot
    team_stats["sca"] = team_shots_sca
    team_stats["gca"] = team_shots_gca
    team_stats["npxG"] = team_shots_npxG
    team_stats["xA"] = team_shots_xA
    team_stats["points"] = team_points
    return team_stats

In [3]:
# print(df_mls)
calc_feats(df_mls, "philadelphia")

{'team': 'philadelphia',
 'shots': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'shots_ot': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'sca': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'gca': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'npxG': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'xA': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64,
 'points': Unnamed: 0    0.0
 Team          0.0
 Season        0.0
 npxG          0.0
 SCA           0.0
 GCA           0.0
 GF            0.0
 Sh            0.0
 xA            0.0
 SoT           0.0
 Pts           0.0
 dtype: float64}

In [4]:
all_teams_stats = []

for team in all_teams:
    team_stats = calc_feats(df_mls, team)
    all_teams_stats.append(team_stats)

df_all_stats = pd.DataFrame(all_teams_stats)
df_all_stats

                      team  shots  shots_ot   sca  gca   npxG     xA  points
0              cf montreal   1439       462  2520  286  156.4  104.6     159
1           houston dynamo   1667       565  2945  288  177.8  119.0     129
2               toronto fc   1540       561  2767  317  177.6  141.3     158
3                fc dallas   1660       569  2913  293  179.5  113.9     172
4           atlanta united   1660       581  3034  326  184.6  126.9     200
5   new england revolution   1759       582  3094  325  185.3  131.7     191
6          colorado rapids   1553       516  2695  298  160.4   99.1     162
7              d.c. united   1469       482  2614  308  153.4  106.3     169
8       philadelphia union   1660       586  2923  338  183.7  138.2     206
9             orlando city   1478       496  2603  307  160.0  125.8     157
10    sporting kansas city   1841       617  3242  357  198.7  136.3     197
11            chicago fire   1599       542  2830  287  176.6  130.5     131
12        seattle sounders   1543       513  2720  332  172.4  134.3     214
13          real salt lake   1604       575  2852  304  158.1  107.9     172
14               la galaxy   1554       543  2842  361  177.5  141.8     169
15        portland timbers   1710       583  3070  341  181.5  139.2     197
16    san jose earthquakes   1775       607  3104  295  172.5  117.2     136
17           columbus crew   1520       485  2748  270  157.4  112.1     177
18        minnesota united   1630       510  2841  287  180.1  120.2     172
19          los angeles fc   2001       714  3516  422  233.1  166.0     206
20            ny red bulls   1627       544  2783  304  180.3  131.1     199
21                   nycfc   1900       678  3324  347  197.0  144.2     210
22     vancouver whitecaps   1302       444  2301  272  141.6   96.4     157
23           fc cincinnati    988       312  1744  128   93.3   61.7      60
24            nashville sc    724       272  1223  135   73.0   46.9      86
25             inter miami    619       207  1069  100   63.8   46.3      65
26               austin fc    448       148   805   59   44.7   36.5      31

In [5]:
df_all_stats.to_csv("../../data/MLS_1823_stats.csv")