In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['axes.grid'] ="True"
mpl.rcParams['axes.spines.top'] = "True"
mpl.rcParams['axes.spines.right'] = "True"
mpl.rcParams['xtick.labelsize'] = 20
mpl.rcParams['ytick.labelsize'] = 20

df_mls = pd.read_csv("../../data/MLS_1823_clean.csv")
df_mls.replace('Montreal Impact', 'CF MontrÃ©al',  inplace=True)
df_mls.replace('CF Montréal', 'CF MontrÃ©al',  inplace=True)
df_mls.replace('Dynamo FC', 'Dynamo',  inplace=True)
df_mls = df_mls[(df_mls['Season'] != 2023) & (df_mls['Season'] != 2022)]

df_mls_matches = pd.read_csv("../../data/MLS_Matches_1823_clean.csv")
df_mls_matches.replace('Montreal Impact', 'CF MontrÃ©al',  inplace=True)
df_mls_matches.replace('Dynamo FC', 'Dynamo',  inplace=True)
df_mls_matches = df_mls_matches[(df_mls_matches['Season_x'] != 2023) & (df_mls_matches['Season_x'] != 2022)]




all_teams = df_mls["Team"].unique()

print(len(df_mls_matches["Team"].unique()))
print(len(all_teams))
print(df_mls_matches)
print(df_mls_matches["Team"].unique())
# print(all_teams)

27
27
     Unnamed: 0             Team               Opp  Season_x  npxG  SCA  GCA  \
0             0      Atlanta Utd       D.C. United      2021   3.2   28    5
1             1      Atlanta Utd         Nashville      2021   0.6   19    0
2             2    Columbus Crew     FC Cincinnati      2021   2.6   38    4
3             3    Columbus Crew           Seattle      2021   0.9   19    1
4             4      Atlanta Utd    Los Angeles FC      2021   1.1   18    2
..          ...              ...               ...       ...   ...  ...  ...
533          98      Sporting KC    Real Salt Lake      2021   0.2    7    2
534          99  Colorado Rapids  Portland Timbers      2021   1.2   19    0
535         100            NYCFC       Atlanta Utd      2021   1.1   21    3
536         101      Atlanta Utd      Orlando City      2020   0.5   19    2
537         102      Atlanta Utd     FC Cincinnati      2020   0.4   14    0

     GF  Sh.2   xA  SoT Result        Date  Season_y             Home Team  \
0     3    16  2.0    6  W 3-2  2021-09-18      2021           Atlanta Utd
1     0    10  1.0    2  L 0-2  2021-08-28      2021           Atlanta Utd
2     3    22  0.8   11  W 3-2  2021-08-27      2021         Columbus Crew
3     1    11  0.5    2  L 1-2  2021-08-21      2021         Columbus Crew
4     1     9  0.4    6  W 1-0  2021-08-15      2021           Atlanta Utd
..   ..   ...  ...  ...    ...         ...       ...                   ...
533   1     4  0.4    1  L 1-2  2021-11-28      2021  Sporting Kansas City
534   0    10  1.0    3  L 0-1  2021-11-25      2021       Colorado Rapids
535   2    13  1.0    5  W 2-0  2021-11-21      2021         New York City
536   1    11  0.5    4  L 1-3  2020-08-29      2020           Atlanta Utd
537   0     8  0.3    3  L 0-1  2020-07-16      2020           Atlanta Utd

            Away Team  Industry Average Away Team Win Odds (American)  \
0           DC United                                             240
1        Nashville SC                                             206
2       FC Cincinnati                                             366
3    Seattle Sounders                                             182
4      Los Angeles FC                                             162
..                ...                                             ...
533    Real Salt Lake                                             458
534  Portland Timbers                                             431
535       Atlanta Utd                                             351
536      Orlando City                                             212
537     FC Cincinnati                                             416

     Industry Average Draw Odds (American)  \
0                                      260
1                                      233
2                                      256
3                                      230
4                                      267
..                                     ...
533                                    313
534                                    305
535                                    272
536                                    249
537                                    300

     Industry Average Home Team Win Odds (American)
0                                               104
1                                               132
2                                              -130
3                                               148
4                                               144
..                                              ...
533                                            -179
534                                            -167
535                                            -132
536                                             120
537                                            -167

[368 rows x 19 columns]
['Atlanta Utd' 'Columbus Crew' 'Chicago Fire' 'FC Dallas' 'Toronto FC'
 'FC Cincinnati' 'Orlando City' 'Real Salt Lake' 'CF MontrÃ©al'
 'Portland Timbers' 'Los Angeles FC' 'Inter Miami' 'Colorado Rapids'
 'D.C. United' 'Nashville' 'Seattle' 'New England' 'San Jose' 'Vancouver'
 'Philadelphia' 'NY Red Bulls' 'Sporting KC' 'NYCFC' 'Minnesota Utd'
 'LA Galaxy' 'Austin' 'Dynamo']

In [5]:
def calc_feats(df, team):
    team_stats = dict()
    df_team = df[(df["Team"]==team)]
    team_shots = df_team.apply(lambda x: x["Sh"], axis=1).sum()
    team_shots_ot = df_team.apply(lambda x: x["SoT"], axis=1).sum()
    team_shots_sca = df_team.apply(lambda x: x["SCA"], axis=1).sum()
    team_shots_gca = df_team.apply(lambda x: x["GCA"], axis=1).sum()
    team_shots_npxG = df_team.apply(lambda x: x["npxG"], axis=1).sum()
    team_shots_xA = df_team.apply(lambda x: x["xA"], axis=1).sum()
    team_points = df_team.apply(lambda x: x["Pts"], axis=1).sum()

    team_stats["team"] = team
    team_stats["shots"] = team_shots
    team_stats["shots_ot"] = team_shots_ot
    team_stats["sca"] = team_shots_sca
    team_stats["gca"] = team_shots_gca
    team_stats["npxG"] = team_shots_npxG
    team_stats["xA"] = team_shots_xA
    team_stats["points"] = team_points
    return team_stats

In [6]:
calc_feats(df_mls, "Philadelphia")

{'team': 'Philadelphia',
 'shots': 1660,
 'shots_ot': 586,
 'sca': 2923,
 'gca': 338,
 'npxG': 183.7,
 'xA': 138.20000000000002,
 'points': 206}

In [7]:
all_teams_stats = []

for team in all_teams:
    team_stats = calc_feats(df_mls, team)
    all_teams_stats.append(team_stats)

df_all_stats = pd.DataFrame(all_teams_stats)
df_all_stats

                team  shots  shots_ot   sca  gca   npxG     xA  points
0             Dynamo   1667       565  2945  288  177.8  119.0     129
1         Toronto FC   1540       561  2767  317  177.6  141.3     158
2          FC Dallas   1660       569  2913  293  179.5  113.9     172
3        Atlanta Utd   1660       581  3034  326  184.6  126.9     200
4          Nashville    724       272  1223  135   73.0   46.9      86
5        New England   1759       582  3094  325  185.3  131.7     191
6    Colorado Rapids   1553       516  2695  298  160.4   99.1     162
7        D.C. United   1469       482  2614  308  153.4  106.3     169
8       Philadelphia   1660       586  2923  338  183.7  138.2     206
9       Orlando City   1478       496  2603  307  160.0  125.8     157
10       Sporting KC   1841       617  3242  357  198.7  136.3     197
11     Columbus Crew   1520       485  2748  270  157.4  112.1     177
12           Seattle   1543       513  2720  332  172.4  134.3     214
13             NYCFC   1900       678  3324  347  197.0  144.2     210
14      NY Red Bulls   1627       544  2783  304  180.3  131.1     199
15    Los Angeles FC   2001       714  3516  422  233.1  166.0     206
16     Minnesota Utd   1630       510  2841  287  180.1  120.2     172
17         Vancouver   1302       444  2301  272  141.6   96.4     157
18            Austin    448       148   805   59   44.7   36.5      31
19          San Jose   1775       607  3104  295  172.5  117.2     136
20       Inter Miami    619       207  1069  100   63.8   46.3      65
21  Portland Timbers   1710       583  3070  341  181.5  139.2     197
22         LA Galaxy   1554       543  2842  361  177.5  141.8     169
23     FC Cincinnati    988       312  1744  128   93.3   61.7      60
24    Real Salt Lake   1604       575  2852  304  158.1  107.9     172
25      Chicago Fire   1599       542  2830  287  176.6  130.5     131
26      CF MontrÃ©al   1439       462  2520  286  156.4  104.6     159

In [5]:
df_all_stats.to_csv("../../data/MLS_1823_stats.csv")